### ISSUE TITLE
Change the twitter widget  follow @kdeindia tweets or the event hashtag

### ISSUE THREAD

**Issue by tinvaan** [amfoss/kdeconf#11]
Find out the official event hashtag and tweak the widget accordingly.

**Comment by a0xnirudh** [comment]
Do we have a twitter account for the conference ?

**Comment by tinvaan** [comment]
Yes, we do. Look for @kdeindia on twitter. Try this : http://twitter.com/kdeindia 
Not sure about the link, twitter is blocked here :\

**Comment by tinvaan** [comment]
Sorry for reporting an already reported issue in : https://github.com/amfoss/kdeconf/issues/8
I'm closing this.
